# Generated by Django 3.0.8 on 2020-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200718_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('password1', models.CharField(max_length=200, verbose_name='Пароль_1')),
                ('password2', models.CharField(max_length=200, verbose_name='Пароль_2')),
            ],
        ),
    ]
